const styles = {
  container: {
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    minHeight: '100vh',
    backgroundColor: '#000',
  },
  navbar: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    zIndex: 100,
    height: '80px',
  transition: "all 0.3s ease",
  },
  navbarTransparent: {
  backgroundColor: "transparent",
  boxShadow: "none",
},

navbarScrolled: {
  backgroundColor: "#ffffff",
  boxShadow: "0 2px 10px rgba(0,0,0,0.08)",
},
navbarScrolledText: {
  color: "#000",
},
  navbarBg: {
    position: 'absolute',
    inset: 0,
    overflow: 'hidden',
  },
  navbarImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    opacity: 0.5,
  },
  navbarOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(to right, rgba(0,0,0,0.6), rgba(0,0,0,0.3))',
  },
  navContent: {
    position: 'relative',
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '0 2rem',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  leftSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '3rem',
  },
  logo: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    cursor: 'pointer',
  },
  logoIcon: {
    width: '32px',
    height: '32px',
    backgroundColor: '#fff',
    color: '#000',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 900,
    borderRadius: '4px',
  },
  logoText: {
    fontSize: '1.5rem',
    fontWeight: 900,
    color: '#fff',
    letterSpacing: '-0.5px',
  },
  logoImage: {
    width: '40px',
    height: '40px',
    objectFit: 'contain',
    borderRadius: '4px',
  },
  menu: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
  },
  menuItem: {
    position: 'relative',
  },
  menuButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    background: 'none',
    border: 'none',
    color: 'rgba(255,255,255,0.9)',
    fontSize: '0.875rem',
    fontWeight: 600,
    cursor: 'pointer',
    padding: '0.5rem 0',
  },

menuButtonScrolled: {
  color: "#000", // 👈 when navbar is scrolled
},

iconButton: {
  background: "none",
  border: "none",
  cursor: "pointer",
  color: "#fff",
},

iconButtonScrolled: {
  color: "#000",
},

loginButton: {
  background: "transparent",
  border: "1px solid #fff",
  color: "#fff",
  padding: "6px 12px",
  borderRadius: "6px",
  cursor: "pointer",
  display: "flex",
  alignItems: "center",
  gap: "6px",
},

loginButtonScrolled: {
  border: "1px solid #000",
  color: "#000",
},

  chevron: {
    marginLeft: '0.25rem',
  },
  liveIndicator: {
    width: '8px',
    height: '8px',
    backgroundColor: '#dc2626',
    borderRadius: '50%',
    animation: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
  },
  badge: {
    backgroundColor: '#ea580c',
    fontSize: '10px',
    padding: '2px 8px',
    borderRadius: '12px',
    fontWeight: 700,
    marginLeft: '0.5rem',
  },
  dropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    width: '256px',
    backgroundColor: '#fff',
    color: '#000',
    boxShadow: '0 20px 25px -5px rgba(0,0,0,0.1), 0 10px 10px -5px rgba(0,0,0,0.04)',
    borderRadius: '12px',
    padding: '1rem 0',
    marginTop: '0.5rem',
    listStyle: 'none',
  },
  dropdownItem: {
    padding: '0.5rem 1.5rem',
    fontSize: '0.875rem',
    cursor: 'pointer',
  },
  rightSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.25rem',
    color: '#fff',
  },
  // iconButton: {
  //   padding: '0.5rem',
  //   background: 'none',
  //   border: 'none',
  //   color: '#fff',
  //   cursor: 'pointer',
  //   borderRadius: '50%',
  // },
  cartContainer: {
    position: 'relative',
    padding: '0.5rem',
    cursor: 'pointer',
  },
  cartBadge: {
    position: 'absolute',
    top: '-4px',
    right: '-4px',
    backgroundColor: '#ea580c',
    fontSize: '10px',
    width: '16px',
    height: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    fontWeight: 700,
  },
  // loginButton: {
  //   display: 'flex',
  //   alignItems: 'center',
  //   gap: '0.5rem',
  //   backgroundColor: 'rgba(255,255,255,0.1)',
  //   backdropFilter: 'blur(12px)',
  //   border: '1px solid rgba(255,255,255,0.2)',
  //   padding: '0.5rem 1.25rem',
  //   borderRadius: '24px',
  //   color: '#fff',
  //   fontWeight: 700,
  //   fontSize: '0.875rem',
  //   cursor: 'pointer',
  // },
  hero: {
    position: 'relative',
    minHeight: '100vh',
    paddingTop: '120px',
    paddingBottom: '80px',
    overflow: 'hidden',
  },
  heroBg: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    opacity: 0.5,
    borderRadius: '24px',
  },
  heroOverlay: {
    position: 'absolute',
    inset: 0,
    borderRadius: '24px',
  },
  heroContent: {
    position: 'relative',
    zIndex: 20,
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '0 2rem',
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '4rem',
    alignItems: 'start',
  },
  leftContent: {
    paddingTop: '2rem',
  },
  heading: {
    fontSize: '5rem',
    fontWeight: 900,
    color: '#fff',
    lineHeight: 1.05,
    marginBottom: '2rem',
  },
  headingAccent: {
    color: '#f97316',
  },
  description: {
    color: '#d1d5db',
    fontSize: '1.125rem',
    marginBottom: '2.5rem',
    maxWidth: '32rem',
    lineHeight: 1.75,
  },
  buttonGroup: {
    display: 'flex',
    gap: '1rem',
    marginBottom: '4rem',
    flexWrap: 'wrap',
  },
  primaryButton: {
    backgroundColor: '#000',
    border: '1px solid rgba(255,255,255,0.2)',
    color: '#fff',
    padding: '1rem 2.5rem',
    borderRadius: '12px',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    cursor: 'pointer',
    fontSize: '1rem',
  },
  arrowIcon: {
    marginLeft: '0.5rem',
  },
  secondaryButton: {
    backgroundColor: '#fff',
    color: '#000',
    padding: '1rem 2.5rem',
    borderRadius: '12px',
    fontWeight: 700,
    border: 'none',
    cursor: 'pointer',
    fontSize: '1rem',
  },
  stats: {
    display: 'flex',
    gap: '3rem',
  },
  statItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  statIcon: {
    padding: '0.75rem',
    backgroundColor: 'rgba(234, 88, 12, 0.2)',
    borderRadius: '8px',
    color: '#f97316',
  },
  statNumber: {
    fontSize: '1.5rem',
    fontWeight: 900,
    color: '#fff',
    margin: 0,
  },
  statLabel: {
    color: '#6b7280',
    fontSize: '0.75rem',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    margin: 0,
  },
  rightCards: {
    paddingTop: '2rem',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  cardsSectionTitle: {
    color: '#fff',
    fontSize: '1.5rem',
    fontWeight: 700,
    marginBottom: '1.5rem',
    textAlign: 'center',
    width: '50%',
  },
  cardsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '1.5rem',
  },
  productCard: {
    position: 'relative',
    width: '230px',
    height: '280px',
    borderRadius: '18px',
    overflow: 'hidden',
    cursor: 'pointer',
    transition: 'transform 0.3s ease',
  },
  cardHover: {
    transform: 'translateY(-6px)',
  },
  productImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  cardOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(to top, rgba(0,0,0,0.7), rgba(0,0,0,0.2))',
  },
  productName: {
    position: 'absolute',
    bottom: '2.5rem',
    left: '0.75rem',
    right: '0.75rem',
    color: '#fff',
    fontWeight: 700,
    fontSize: '0.875rem',
    textAlign: 'center',
    zIndex: 2,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  priceTag: {
    position: 'absolute',
    top: '0.75rem',
    right: '0.75rem',
    backgroundColor: '#10b981',
    color: '#fff',
    fontWeight: 700,
    padding: '0.25rem 0.6rem',
    borderRadius: '6px',
    fontSize: '0.75rem',
    zIndex: 2,
  },
  timeTag: {
    position: 'absolute',
    bottom: '0.75rem',
    left: '0.75rem',
    right: '0.75rem',
    backgroundColor: 'rgba(0,0,0,0.75)',
    color: '#fff',
    padding: '0.4rem 0.6rem',
    borderRadius: '8px',
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '10px',
    zIndex: 2,
  },
  timeValue: {
    fontWeight: 700,
    color: '#f97316',
  },
  bigTypography: {
    position: 'absolute',
    bottom: '2.5rem',
    right: '3rem',
    zIndex: 10,
    textAlign: 'right',
  },
  bigNumber: {
    fontSize: '4.5rem',
    fontWeight: 900,
    color: 'rgba(255,255,255,0.2)',
    lineHeight: 1,
    margin: 0,
  },
  bigLabel: {
    fontSize: '1.25rem',
    letterSpacing: '0.2em',
    color: 'rgba(255,255,255,0.4)',
    textTransform: 'uppercase',
    margin: 0,
  },
};

export default styles;
