// components/checkout/steps/constants/ShippingFields.js
export const SHIPPING_FIELDS = [
  {
    id: "fullName",
    label: "Full name",
    placeholder: "",
    icon: "👤",
    fullWidth: true,
    required: true,
    autoComplete: "name",
  },
  {
    id: "email",
    label: "Email",
    placeholder: "",
    icon: "📧",
    fullWidth: true,
    required: true,
    type: "email",
    autoComplete: "email",
  },
  {
    id: "address",
    label: "Street address",
    placeholder: "123 Main Street",
    icon: "🏠",
    fullWidth: true,
    required: true,
    autoComplete: "street-address",
  },
  {
    id: "city",
    label: "City",
    placeholder: "",
    icon: "🏙️",
    fullWidth: false,
    required: true,
    autoComplete: "address-level2",
  },
  {
    id: "zip",
    label: "Postal / ZIP code",
    placeholder: "",
    icon: "📮",
    fullWidth: false,
    required: true,
    autoComplete: "postal-code",
  },
  {
    id: "state",
    label: "State / Province",
    placeholder: "",
    icon: "🗺️",
    fullWidth: true,
    required: true,
    autoComplete: "address-level1",
  },
  {
    id: "phone",
    label: "Phone Number",
    placeholder: "",
    icon: "📞",
    fullWidth: true,
    required: true,
    type: "tel",
    autoComplete: "tel",
  },
];
